### PR TITLE
Update staff

### PR DESCRIPTION
**Pull request by Fjuro**

### CODE REVIEW

**Comment by Vladimir-Urik** [comment]
Please use this specific form:

```md
<!--- Provide a general summary of your changes in the Title above -->

## Description
<!--- Describe your changes in detail -->

## Motivation and Context
<!--- Why is this change required? What problem does it solve? -->
<!--- If it fixes an open issue, please link to the issue here. -->

## How Has This Been Tested?
<!--- Please describe in detail how you tested your changes. -->
<!--- Include details of your testing environment, and the tests you ran to -->
<!--- see how your change affects other areas of the code, etc. -->

## Screenshots (if appropriate):

## Types of changes
<!--- What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I used `yarn` to build and test the project.
- [ ] I tested the build on my local machine and it works.
```

**Comment by Fjuro** [comment]
## Description
Removed Erik and lutysek, changed Fjuro to manager

## Motivation and Context
Changes in staff team

## How Has This Been Tested?
It has not

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Small change

## Checklist:


- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I used `yarn` to build and test the project.
- [ ] I tested the build on my local machine and it works.

**Comment by Vladimir-Urik** [comment]
Okay, test the project first.

**Comment by Vladimir-Urik** [comment]
Since the new ateams manager is too lazy to test, I'm merging the PR. Unfortunately, it's anarchy.

**Pull request merged**
